version: "3.8"

services:

    consul:
        image: consul
        container_name: consul
        restart: unless-stopped
        networks:
          - pizzaitaliano
        ports:
          - 8500:8500
        # volumes:
        #   - consul:/consul/data

    fabio:
        image: fabiolb/fabio
        container_name: fabio
        restart: unless-stopped
        environment:
        - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
        networks:
          - pizzaitaliano
        ports:
        - 9998:9998
        - 9999:9999

    rabbitmq:
        build: ./rabbitmq
        container_name: rabbitmq
        restart: unless-stopped
        networks:
          - pizzaitaliano
        ports:
          - 5672:5672
          - 15672:15672
          - 15692:15692
        # volumes: 
        #   - rabbitmq:/var/lib/rabbitmq
    
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        # environment:
        #   - MONGO_INITDB_ROOT_USERNAME=root
        #   - MONGO_INITDB_ROOT_PASSWORD=secret
        networks:
          - pizzaitaliano
        ports:
          - 27017:27017
        volumes:
          - mongo:/data/db
    seq:
        image: datalust/seq 
        container_name: seq
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        networks:
          - pizzaitaliano
        ports:         
         - 5341:80
        # volumes: 
        #   - seq:/data
    
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        networks:
          - pizzaitaliano
        ports:
          - 6379:6379
        volumes: 
          - redis:/data

    vault:
        image: vault
        container_name: vault
        restart: unless-stopped
        environment:
          - VAULT_ADDR=http://127.0.0.1:8200
          - VAULT_DEV_ROOT_TOKEN_ID=secret
        cap_add:
          - IPC_LOCK
        networks:
          - pizzaitaliano
        ports:
          - 8200:8200

    
networks:
  pizzaitaliano:
    name: pizza-italiano-network

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  mongo:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local
  