global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:5000']
      
  - job_name: 'product-service'
    static_configs:
      - targets: ['host.docker.internal:5001']    

  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:5002']
      
  - job_name: 'release-service'
    static_configs:
      - targets: ['host.docker.internal:5003']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:5004']

  - job_name: 'operation-service'
    static_configs:
      - targets: ['host.docker.internal:5005']
      
  - job_name: 'identity-service'
    static_configs:
      - targets: ['host.docker.internal:5006']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']