global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway']
      
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service']
      
  - job_name: 'release-service'
    static_configs:
      - targets: ['release-service']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service']

  - job_name: 'operations-service'
    static_configs:
      - targets: ['operations-service']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']